### ISSUE TITLE
Confusing word: Policy

### ISSUE THREAD

**Issue by gmiranda23** [chef-training/chefdk-fundamentals#24]
We've started using the terms "Policy" and "Data" to describe data-driven cookbooks: separate the data from the recipe.  In classes where I've used the basis of the v3 materials, the word "policy" creates confusion.  While we use "policy" a bit loosely, the real kicker is students that have some basic Chef exposure start asking about "Policyfiles".

Perhaps we should consider using something like "Pattern" and "Data" (e.g. separate the data of what to do from the pattern of how to do it).  Or maybe "Code" and "Data".  But, unfortunately, "Policy" now has a specific meaning in Chef and it's not a synonym for "recipe".

**Comment by nathenharvey** [comment]
Maybe we call it "desired state"?  The recipes, roles, etc., define the "desired state" of our infrastructure.  This desired state can be driven by data.

Also, the Chef server stores both the "desired state" of our infrastructure (previously referred to as 'policy') and the "current state" of our infrastructure (previously referred to as 'state').

**Comment by gmiranda23** [comment]
:+1:

**Comment by nathenharvey** [comment]
there's also an RFC about actually making this distinction between desired and current more obvious.  https://github.com/chef/chef-rfc/blob/master/rfc045-node_state_separation.md
