### ISSUE TITLE
Typo -- Slide 181

### ISSUE THREAD

**Issue by gmiranda23** [chef-training/chefdk-fundamentals#34]
Ubuntu 14.04 is set.  Titlebar reads 12.04.

I'd submit a PR, but I wasn't sure how are you handling versioning binary files?  Can you make that clear in the README?  If everyone submits updates to the .pptx file via git, I think this repo is likely going to get unwieldy pretty quickly.

**Comment by burtlo** [comment]
I'll fix this issue.

Binary files are still a pain. I'll add some more information to README.

**Comment by burtlo** [comment]
FIX in commit 28d9571a5ba0b328953d6e7e836f1163de6e8ca2
